-- Deprecated AI layer migration (no-op)
--
-- This historical file used to create the legacy ai_sessions/session_id model.
-- The live Supabase schema was superseded by the ai_conversations/conversation_id
-- model, applied in production via Supabase migration:
--   20260605191259 ai_layer_alignment_conversations_model_phase1
--
-- Keep this file only for lineage. Do not add active DDL here, because replaying
-- it would recreate obsolete objects that no longer match the live database.
