-- Agent learning, connector memory and continuous improvement foundation

create table if not exists connector_payload_cache (
  id uuid primary key default gen_random_uuid(),
  source_endpoint_id text not null references source_endpoints(id) on delete cascade,
  cache_key text not null,
  payload jsonb not null default '{}'::jsonb,
  payload_hash text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists uq_connector_payload_cache on connector_payload_cache(source_endpoint_id, cache_key);

create table if not exists agent_memory (
  id uuid primary key default gen_random_uuid(),
  agent_name text not null,
  memory_type text not null,
  company_id text references companies(id) on delete set null,
  source_ref text,
  importance numeric(5,4) not null default 0.50,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_agent_memory_agent_created on agent_memory(agent_name, created_at desc);
create index if not exists idx_agent_memory_company on agent_memory(company_id, created_at desc);

create table if not exists agent_feedback (
  id uuid primary key default gen_random_uuid(),
  agent_name text not null,
  company_id text references companies(id) on delete set null,
  feedback_type text not null,
  score integer,
  note text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_agent_feedback_agent_created on agent_feedback(agent_name, created_at desc);

create table if not exists agent_improvement_backlog (
  id uuid primary key default gen_random_uuid(),
  agent_name text not null,
  improvement_title text not null,
  priority text not null default 'medium',
  status text not null default 'open',
  rationale text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_agent_improvement_backlog_status on agent_improvement_backlog(status, priority);

comment on table connector_payload_cache is 'Reusable cache for connector responses and scraping payloads.';
comment on table agent_memory is 'Persistent learning memory for agents across company workflows.';
comment on table agent_feedback is 'Structured human or system feedback for agent learning loops.';
comment on table agent_improvement_backlog is 'Continuous improvement backlog generated by learning agents.';
