-- Institutional source catalog expansion for Motor Originação SRM.
-- Goal: convert the data-source map into governed, monitorable Supabase seed data.
-- This migration is intentionally idempotent and supports both historical text-id
-- catalog schemas and the production uuid-id catalog observed in runtime notes.

do $$
declare
  source_id_type text;
begin
  select data_type
    into source_id_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'source_catalog'
    and column_name = 'id';

  if source_id_type = 'uuid' then
    insert into public.source_catalog (name, source_type, category, auth_requirement, status, metadata, rate_limit_notes, health)
    values
      ('Receita Federal CNPJ Dataset', 'batch_api', 'company_registry', 'none', 'real', '{"code":"src_receita_federal_cnpj_dataset","priority":100,"refreshCadence":"monthly","sourceConfidence":"high","signals":["company_identity","entity_resolution","cnae_sector","legal_status"],"fields":["cnpj","legal_name","trade_name","cnae","legal_status","opening_date","partners"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Public federal dataset. Prefer batch ingestion and avoid repeated online lookups.', 'healthy'),
      ('CVM Dados Abertos Fundos e Ofertas', 'batch_api', 'capital_markets', 'none', 'real', '{"code":"src_cvm_open_data_funds_offers","priority":100,"refreshCadence":"daily_or_weekly","sourceConfidence":"very_high","signals":["existing_fidc","structured_fund_presence","capital_markets_activity","dcm_comparable"],"fields":["fund_registry","fidc","offer","issuer","participant","document_url"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Use CVM open-data files as source of truth for funds, offerings and regulated capital-market evidence.', 'healthy'),
      ('Banco Central IFData e Instituições Autorizadas', 'api', 'central_bank', 'none', 'real', '{"code":"src_bcb_ifdata_authorized_institutions","priority":95,"refreshCadence":"quarterly_or_monthly","sourceConfidence":"very_high","signals":["regulatory_license","regulated_financial_activity","complaint_risk"],"fields":["institution","authorization_type","segment","complaints","ifdata_metrics"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Official source for financial institutions, payment institutions and selected supervisory signals.', 'healthy'),
      ('ANBIMA Fundos Estruturados', 'api', 'funds_structured', 'none', 'real', '{"code":"src_anbima_structured_funds","priority":95,"refreshCadence":"weekly","sourceConfidence":"high","signals":["existing_fidc","fidc_comparable","fund_service_provider","structured_fund_presence"],"fields":["fund_name","class","subclass","administrator","manager","custodian","fund_type"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Use for FIDC/FII/FIP structured-fund comparables and service-provider mapping.', 'healthy'),
      ('B3 Emissores e Fatos Relevantes', 'crawler', 'capital_markets', 'none', 'real', '{"code":"src_b3_issuers_material_facts","priority":85,"refreshCadence":"daily_or_weekly","sourceConfidence":"high","signals":["public_debt_signal","corporate_event","dcm_comparable","governance_signal"],"fields":["issuer","ticker","material_fact","document_url","published_at"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Relevant for public-company comparables, governance events and debt-market context.', 'healthy'),
      ('Open Finance Brasil Participantes', 'api', 'open_finance', 'none', 'real', '{"code":"src_open_finance_participants","priority":80,"refreshCadence":"monthly","sourceConfidence":"high","signals":["regulated_financial_activity","open_finance_participant","financial_product_surface"],"fields":["participant","brand","products","apis","authorization"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Maps regulated participants and financial-product surfaces exposed publicly.', 'healthy'),
      ('VC Portfolio Monitor Brasil', 'crawler', 'vc_portfolio', 'none', 'real', '{"code":"src_vc_portfolio_monitor_br","priority":90,"refreshCadence":"weekly","sourceConfidence":"medium_high","signals":["vc_backed_growth_signal","growth_signal","cap_table_quality","approach_trigger"],"targetFunds":["Kaszek","Monashees","Canary","Astella","Valor Capital","Redpoint eventures","ABSeed","ONEVC","Norte Ventures","Upload Ventures","Iporanga","MAYA Capital","Domo"],"governance":{"observedVsInferred":"observed_and_inferred","lineageRequired":true}}'::jsonb, 'Strategic discovery layer for tech-backed companies before explicit funding demand.', 'healthy'),
      ('Company Careers and Jobs Monitor', 'crawler', 'jobs', 'none', 'real', '{"code":"src_company_jobs_monitor","priority":80,"refreshCadence":"weekly","sourceConfidence":"medium","signals":["credit_team_expansion","finance_org_building","growth_signal","approach_trigger"],"keywords":["Treasury","Funding","Capital Markets","Credit Risk","Underwriting","Collections","Cobrança","FP&A","CFO","Head of Finance","FIDC"],"governance":{"observedVsInferred":"observed_and_inferred","lineageRequired":true}}'::jsonb, 'Detects weak timing signals through hiring for credit, risk, treasury and finance teams.', 'healthy'),
      ('Procurement and Public Contracts Monitor', 'api', 'government_contracts', 'none', 'planned', '{"code":"src_public_procurement_contracts","priority":70,"refreshCadence":"monthly","sourceConfidence":"high","signals":["government_receivables","recurring_contracts","b2g_revenue_signal"],"sources":["PNCP","Compras.gov","Portal da Transparência"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Phase 2 source for B2G receivables and recurring public-sector contracts.', 'healthy'),
      ('Origination Google Dorks Monitor', 'search_dork', 'search_dork', 'none', 'planned', '{"code":"src_origination_google_dorks","priority":75,"refreshCadence":"manual_or_weekly","sourceConfidence":"medium","signals":["documented_credit_structure","existing_fidc","existing_debt","hidden_company_document"],"queryTemplates":["{company} FIDC","{company} direitos creditórios","{company} debênture","{company} nota comercial","{company} recebíveis filetype:pdf"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Discovery layer for public PDFs, decks and semi-hidden institutional pages.', 'healthy')
    on conflict (name) do update set
      source_type = excluded.source_type,
      category = excluded.category,
      auth_requirement = excluded.auth_requirement,
      status = excluded.status,
      metadata = excluded.metadata,
      rate_limit_notes = excluded.rate_limit_notes,
      health = excluded.health,
      updated_at = now();
  else
    insert into public.source_catalog (id, name, source_type, category, auth_requirement, status, metadata, rate_limit_notes, health)
    values
      ('src_receita_federal_cnpj_dataset', 'Receita Federal CNPJ Dataset', 'batch_api', 'company_registry', 'none', 'real', '{"code":"src_receita_federal_cnpj_dataset","priority":100,"refreshCadence":"monthly","sourceConfidence":"high","signals":["company_identity","entity_resolution","cnae_sector","legal_status"],"fields":["cnpj","legal_name","trade_name","cnae","legal_status","opening_date","partners"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Public federal dataset. Prefer batch ingestion and avoid repeated online lookups.', 'healthy'),
      ('src_cvm_open_data_funds_offers', 'CVM Dados Abertos Fundos e Ofertas', 'batch_api', 'capital_markets', 'none', 'real', '{"code":"src_cvm_open_data_funds_offers","priority":100,"refreshCadence":"daily_or_weekly","sourceConfidence":"very_high","signals":["existing_fidc","structured_fund_presence","capital_markets_activity","dcm_comparable"],"fields":["fund_registry","fidc","offer","issuer","participant","document_url"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Use CVM open-data files as source of truth for funds, offerings and regulated capital-market evidence.', 'healthy'),
      ('src_bcb_ifdata_authorized_institutions', 'Banco Central IFData e Instituições Autorizadas', 'api', 'central_bank', 'none', 'real', '{"code":"src_bcb_ifdata_authorized_institutions","priority":95,"refreshCadence":"quarterly_or_monthly","sourceConfidence":"very_high","signals":["regulatory_license","regulated_financial_activity","complaint_risk"],"fields":["institution","authorization_type","segment","complaints","ifdata_metrics"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Official source for financial institutions, payment institutions and selected supervisory signals.', 'healthy'),
      ('src_anbima_structured_funds', 'ANBIMA Fundos Estruturados', 'api', 'funds_structured', 'none', 'real', '{"code":"src_anbima_structured_funds","priority":95,"refreshCadence":"weekly","sourceConfidence":"high","signals":["existing_fidc","fidc_comparable","fund_service_provider","structured_fund_presence"],"fields":["fund_name","class","subclass","administrator","manager","custodian","fund_type"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Use for FIDC/FII/FIP structured-fund comparables and service-provider mapping.', 'healthy'),
      ('src_b3_issuers_material_facts', 'B3 Emissores e Fatos Relevantes', 'crawler', 'capital_markets', 'none', 'real', '{"code":"src_b3_issuers_material_facts","priority":85,"refreshCadence":"daily_or_weekly","sourceConfidence":"high","signals":["public_debt_signal","corporate_event","dcm_comparable","governance_signal"],"fields":["issuer","ticker","material_fact","document_url","published_at"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Relevant for public-company comparables, governance events and debt-market context.', 'healthy'),
      ('src_open_finance_participants', 'Open Finance Brasil Participantes', 'api', 'open_finance', 'none', 'real', '{"code":"src_open_finance_participants","priority":80,"refreshCadence":"monthly","sourceConfidence":"high","signals":["regulated_financial_activity","open_finance_participant","financial_product_surface"],"fields":["participant","brand","products","apis","authorization"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Maps regulated participants and financial-product surfaces exposed publicly.', 'healthy'),
      ('src_vc_portfolio_monitor_br', 'VC Portfolio Monitor Brasil', 'crawler', 'vc_portfolio', 'none', 'real', '{"code":"src_vc_portfolio_monitor_br","priority":90,"refreshCadence":"weekly","sourceConfidence":"medium_high","signals":["vc_backed_growth_signal","growth_signal","cap_table_quality","approach_trigger"],"targetFunds":["Kaszek","Monashees","Canary","Astella","Valor Capital","Redpoint eventures","ABSeed","ONEVC","Norte Ventures","Upload Ventures","Iporanga","MAYA Capital","Domo"],"governance":{"observedVsInferred":"observed_and_inferred","lineageRequired":true}}'::jsonb, 'Strategic discovery layer for tech-backed companies before explicit funding demand.', 'healthy'),
      ('src_company_jobs_monitor', 'Company Careers and Jobs Monitor', 'crawler', 'jobs', 'none', 'real', '{"code":"src_company_jobs_monitor","priority":80,"refreshCadence":"weekly","sourceConfidence":"medium","signals":["credit_team_expansion","finance_org_building","growth_signal","approach_trigger"],"keywords":["Treasury","Funding","Capital Markets","Credit Risk","Underwriting","Collections","Cobrança","FP&A","CFO","Head of Finance","FIDC"],"governance":{"observedVsInferred":"observed_and_inferred","lineageRequired":true}}'::jsonb, 'Detects weak timing signals through hiring for credit, risk, treasury and finance teams.', 'healthy'),
      ('src_public_procurement_contracts', 'Procurement and Public Contracts Monitor', 'api', 'government_contracts', 'none', 'planned', '{"code":"src_public_procurement_contracts","priority":70,"refreshCadence":"monthly","sourceConfidence":"high","signals":["government_receivables","recurring_contracts","b2g_revenue_signal"],"sources":["PNCP","Compras.gov","Portal da Transparência"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Phase 2 source for B2G receivables and recurring public-sector contracts.', 'healthy'),
      ('src_origination_google_dorks', 'Origination Google Dorks Monitor', 'search_dork', 'search_dork', 'none', 'planned', '{"code":"src_origination_google_dorks","priority":75,"refreshCadence":"manual_or_weekly","sourceConfidence":"medium","signals":["documented_credit_structure","existing_fidc","existing_debt","hidden_company_document"],"queryTemplates":["{company} FIDC","{company} direitos creditórios","{company} debênture","{company} nota comercial","{company} recebíveis filetype:pdf"],"governance":{"observedVsInferred":"observed","lineageRequired":true}}'::jsonb, 'Discovery layer for public PDFs, decks and semi-hidden institutional pages.', 'healthy')
    on conflict (name) do update set
      source_type = excluded.source_type,
      category = excluded.category,
      auth_requirement = excluded.auth_requirement,
      status = excluded.status,
      metadata = excluded.metadata,
      rate_limit_notes = excluded.rate_limit_notes,
      health = excluded.health,
      updated_at = now();
  end if;
end $$;
