create or replace function public.apply_factor_map_lead_adjustments()
returns trigger language plpgsql security definer set search_path=public as $$
declare factor_map jsonb; opportunity numeric:=0; risk_penalty numeric:=0; confidence_value numeric:=0; final_score numeric; bucket_value text;
begin
  factor_map:=public.get_company_factor_map(new.company_id);
  if coalesce((factor_map->>'factorCount')::integer,0)=0 then return new; end if;
  opportunity:=coalesce((factor_map->>'opportunityScore')::numeric,0);
  risk_penalty:=coalesce((factor_map->>'riskPenalty')::numeric,0);
  confidence_value:=coalesce((factor_map->>'sourceConfidence')::numeric,0);
  final_score:=least(100,greatest(0,coalesce(new.lead_score,0)+round(opportunity*0.20)-round(risk_penalty*0.36)));
  if risk_penalty>=28 then final_score:=least(final_score,59); end if;
  bucket_value:=case when final_score>=85 then 'immediate_priority' when final_score>=70 then 'high_priority' when final_score>=55 then 'monitor_closely' when final_score>=40 then 'watchlist' else 'low_priority' end;
  new.lead_score:=final_score; new.priority_tier:=bucket_value; new.bucket:=bucket_value;
  new.source_confidence:=greatest(coalesce(new.source_confidence,0),confidence_value);
  new.trigger_strength:=greatest(coalesce(new.trigger_strength,0),coalesce((factor_map->>'maxFactorScore')::numeric,0));
  new.pattern_score:=coalesce(new.pattern_score,0)+round(opportunity*0.18)-round(risk_penalty*0.22);
  new.suggested_structure:=coalesce(nullif(factor_map->>'recommendedStructure',''),new.suggested_structure);
  new.next_action:=coalesce(factor_map->>'nextAction',new.next_action);
  new.commercial_angle:=coalesce(new.commercial_angle,case when coalesce((factor_map->>'fidcFitDelta')::numeric,0)>=coalesce((factor_map->>'dcmFitDelta')::numeric,0) then 'Abordagem orientada ao ativo e à escalabilidade dos recebíveis.' else 'Abordagem orientada ao perfil de dívida, vencimentos e estrutura de capital.' end);
  new.rationale:=concat(coalesce(new.rationale,''),format(' Factor map: opportunity=%s, risk=%s.',round(opportunity,2),round(risk_penalty,2)));
  return new;
end; $$;

create unique index if not exists uq_tasks_factor_map_task_code on public.tasks((metadata->>'factorMapTaskCode')) where metadata?'factorMapTaskCode';

create or replace function public.sync_factor_map_pipeline_and_tasks()
returns trigger language plpgsql security definer set search_path=public as $$
declare factor_map jsonb; factor_count integer:=0; risk_penalty numeric:=0; action_text text; task_code text; stage_value text; status_value text;
begin
  factor_map:=public.get_company_factor_map(new.company_id);
  factor_count:=coalesce((factor_map->>'factorCount')::integer,0);
  if factor_count=0 then return null; end if;
  risk_penalty:=coalesce((factor_map->>'riskPenalty')::numeric,0);
  action_text:=coalesce(factor_map->>'nextAction','Revisar mapa de fatores e confirmar materialidade.');
  stage_value:=case when risk_penalty>=28 then 'Identified' when new.lead_score>=70 then 'Approach' when new.lead_score>=55 then 'Qualified' else 'Identified' end;
  status_value:=case when risk_penalty>=28 then 'attention' else 'active' end;
  insert into public.pipeline(company_id,stage,status,priority,next_action,expected_structure,notes,created_at,updated_at)
  values(new.company_id,stage_value,status_value,coalesce(new.bucket,new.priority_tier,'watchlist'),action_text,nullif(factor_map->>'recommendedStructure',''),'[signal_factor_map_v1] fatores explicáveis sincronizados automaticamente.',now(),now())
  on conflict(company_id) do update set priority=excluded.priority,next_action=excluded.next_action,expected_structure=coalesce(excluded.expected_structure,public.pipeline.expected_structure),notes=concat_ws(' ',public.pipeline.notes,excluded.notes),updated_at=now();
  task_code:=md5(new.company_id::text||'|'||action_text||'|signal_factor_map_v1');
  insert into public.tasks(company_id,title,description,status,priority,due_at,owner_name,metadata,created_at,updated_at)
  values(new.company_id,'Mapa de fatores · '||left(action_text,160),concat(action_text,' Top factor: ',coalesce(factor_map#>>'{topFactor,name}','não identificado'),'.'),'todo',case when risk_penalty>=18 then 'high' else 'medium' end,now()+interval '3 days',case when risk_penalty>=18 then 'Credit' else 'Intelligence' end,jsonb_build_object('autoGenerated',true,'source','signal_factor_map_v1','factorMapTaskCode',task_code,'factorMap',factor_map),now(),now()) on conflict do nothing;
  return null;
end; $$;

drop trigger if exists capture_signal_factor_observations on public.company_signals;
create trigger capture_signal_factor_observations after insert or update of signal_type,signal_strength,strength,confidence_score,confidence,evidence_payload,metadata on public.company_signals for each row execute function public.capture_signal_factor_observations();
drop trigger if exists enrich_qualification_with_factor_map on public.qualification_snapshots;
create trigger enrich_qualification_with_factor_map before insert on public.qualification_snapshots for each row execute function public.enrich_qualification_with_factor_map();
drop trigger if exists sync_factor_map_patterns on public.qualification_snapshots;
create trigger sync_factor_map_patterns after insert on public.qualification_snapshots for each row execute function public.sync_factor_map_patterns();
drop trigger if exists apply_factor_map_lead_adjustments on public.lead_score_snapshots;
create trigger apply_factor_map_lead_adjustments before insert on public.lead_score_snapshots for each row execute function public.apply_factor_map_lead_adjustments();
drop trigger if exists sync_factor_map_pipeline_and_tasks on public.lead_score_snapshots;
create trigger sync_factor_map_pipeline_and_tasks after insert on public.lead_score_snapshots for each row execute function public.sync_factor_map_pipeline_and_tasks();
