-- The current Knowledge Vault frontend has a closed KnowledgeNodeType union.
-- Represent investors with the existing 'source' node type plus explicit investor tags/properties
-- so the relationship graph renders correctly without introducing a parallel frontend contract.
create or replace function public.sync_people_capital_investor_graph()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_company_node_id uuid;
  v_investor_node_id uuid;
  v_company_name text;
  v_investor_name text;
  v_investor_normalized text;
  v_system_actor uuid := '00000000-0000-0000-0000-000000000001'::uuid;
begin
  select trade_name into v_company_name from public.companies where id=new.company_id;
  select name, normalized_name into v_investor_name, v_investor_normalized from public.investors where id=new.investor_id;

  select id into v_company_node_id from public.knowledge_nodes
  where company_id=new.company_id and node_type='company' and status='active'
  order by updated_at desc limit 1;

  if v_company_node_id is null then
    insert into public.knowledge_nodes (
      title, slug, node_type, content_markdown, excerpt, tags, properties,
      company_id, status, visibility, created_by, updated_by
    ) values (
      coalesce(v_company_name, 'Company'),
      'company-' || new.company_id::text,
      'company',
      '# ' || coalesce(v_company_name, 'Company'),
      'Company node generated by People & Capital Intelligence.',
      array['company','auto-generated'],
      jsonb_build_object('generatedBy','people_capital_intelligence'),
      new.company_id, 'active', 'team', v_system_actor, v_system_actor
    ) returning id into v_company_node_id;
  end if;

  select id into v_investor_node_id from public.knowledge_nodes
  where properties->>'investorId'=new.investor_id::text
    and status='active'
  order by updated_at desc limit 1;

  if v_investor_node_id is null then
    insert into public.knowledge_nodes (
      title, slug, node_type, content_markdown, excerpt, tags, properties,
      status, visibility, created_by, updated_by
    ) values (
      v_investor_name,
      'investor-' || public.knowledge_slugify(coalesce(v_investor_normalized,v_investor_name)) || '-' || left(new.investor_id::text,8),
      'source',
      '# ' || v_investor_name || E'\n\nInvestidor relacionado automaticamente a companhias monitoradas.',
      'Investidor no mapa de capital da Origination Intelligence Platform.',
      array['investor','capital-network','auto-generated'],
      jsonb_build_object(
        'investorId',new.investor_id,
        'semanticNodeType','investor',
        'generatedBy','people_capital_intelligence'
      ),
      'active', 'team', v_system_actor, v_system_actor
    ) returning id into v_investor_node_id;
  end if;

  insert into public.knowledge_links (
    source_node_id, target_node_id, target_title, target_slug, relation_type, properties, created_by
  )
  select
    v_company_node_id, v_investor_node_id, n.title, n.slug, 'backed_by',
    jsonb_build_object(
      'relationshipId',new.id,
      'roundStage',new.round_stage,
      'roundAmount',new.round_amount,
      'roundCurrency',new.round_currency,
      'isLead',new.is_lead,
      'announcedAt',new.announced_at,
      'sourceUrl',new.source_url,
      'confidenceScore',new.confidence_score,
      'semanticTargetType','investor'
    ),
    v_system_actor
  from public.knowledge_nodes n where n.id=v_investor_node_id
  on conflict (source_node_id,target_slug,relation_type)
  do update set target_node_id=excluded.target_node_id, target_title=excluded.target_title, properties=excluded.properties;

  insert into public.knowledge_links (
    source_node_id, target_node_id, target_title, target_slug, relation_type, properties, created_by
  )
  select
    v_investor_node_id, v_company_node_id, n.title, n.slug, 'portfolio_company',
    jsonb_build_object(
      'relationshipId',new.id,
      'sourceUrl',new.source_url,
      'confidenceScore',new.confidence_score,
      'semanticSourceType','investor'
    ),
    v_system_actor
  from public.knowledge_nodes n where n.id=v_company_node_id
  on conflict (source_node_id,target_slug,relation_type)
  do update set target_node_id=excluded.target_node_id, target_title=excluded.target_title, properties=excluded.properties;

  return new;
end;
$$;

-- Defensive backfill in case migrations are replayed over an environment that already received investor nodes.
update public.knowledge_nodes
set node_type='source',
    properties=coalesce(properties,'{}'::jsonb) || jsonb_build_object('semanticNodeType','investor'),
    tags=(select array(select distinct unnest(coalesce(tags,'{}'::text[]) || array['investor','capital-network'])))
where node_type='investor' and properties ? 'investorId';
