import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('signal ingestion only queues heavy company reprocessing', async () => {
  const sql = await read('db/migrations/144_origination_reprocessing_queue.sql');
  assert.match(sql, /origination_reprocessing_queue/);
  assert.match(sql, /enqueue_company_origination_reprocessing/);
  assert.match(sql, /process_origination_reprocessing_queue/);
  assert.doesNotMatch(sql, /perform public\.refresh_company_factor_snapshots\(new\.company_id/i);
  assert.doesNotMatch(sql, /perform public\.refresh_company_origination_brief_v1\(v_company_id\)/i);
});

test('derived reprocessing is bounded and scheduled independently from capture', async () => {
  const sql = await read('db/migrations/145_origination_reprocessing_schedule.sql');
  assert.match(sql, /origination-derived-reprocessing/);
  assert.match(sql, /process_origination_reprocessing_queue\(25\)/);
  assert.match(sql, /\*\/5 \* \* \* \*/);
});

test('final resolver v4 requires verified CNPJ identity and quarantines conflicts', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  assert.match(sql, /candidate_role in \('operating_company','operating_issuer'\)/);
  assert.match(sql, /coalesce\(c\.cnpj_valid,false\)/);
  assert.match(sql, /website_identity_capture,status/);
  assert.match(sql, /canonical_key_conflict/);
  assert.match(sql, /domain_cnpj_conflict/);
  assert.match(sql, /automatic_deterministic_identity_v4/);
  assert.match(sql, /auto_resolve_verified_candidate_entities_v4\(50\)/);
});

test('resolver v4 never writes generated Company Master columns', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  const insertHeader = sql.match(/insert into public\.companies\(([\s\S]*?)\) values/i)?.[1] ?? '';
  for (const generated of ['normalized_name', 'segment', 'subsegment', 'website', 'geography']) {
    assert.doesNotMatch(insertHeader, new RegExp(`\\b${generated}\\b`));
  }
  assert.match(sql, /normalized_name, segment, subsegment, website and geography are generated by PostgreSQL/);
});

test('company changes enqueue derived reprocessing instead of synchronous brief refresh', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  assert.match(sql, /trg_refresh_company_origination_brief_from_company_v2/);
  assert.match(sql, /enqueue_company_origination_reprocessing\(new\.id,'origination_brief_dependency:companies'\)/);
  assert.doesNotMatch(sql, /perform public\.refresh_company_origination_brief_v1\(new\.id\)/);
});

test('verified operating issuers enter origination analytics without becoming credit-approved', async () => {
  const sql = await read('db/migrations/148_operating_issuer_resolution_and_analytics_fix.sql');
  assert.match(sql, /excluded_from_qualification',false/);
  assert.match(sql, /excluded_from_scoring',false/);
  assert.match(sql, /credit_approval_separate',true/);
});

test('verified real entities enter origination analytics without becoming credit-approved', async () => {
  const sql = await read('db/migrations/147_origination_entity_eligibility_gate.sql');
  assert.match(sql, /verified_entity_ready_for_origination_qualification/);
  assert.match(sql, /origination_analytics_eligible/);
  assert.match(sql, /credit_approval_separate/);
  assert.match(sql, /credit_review_status',''\)<>'rejected'/);
});

test('candidate promotion refreshes monitoring and recomputes downstream artifacts', async () => {
  const service = await read('backend/src/services/searchProfileCaptureService.ts');
  assert.match(service, /derivedDataRecomputed/);
  assert.match(service, /await this\.hooks\.recomputeDerivedData\(companyId\)/);
  assert.doesNotMatch(service, /recomputeDerivedDataSkipped:\s*true/);
  assert.doesNotMatch(service, /derivedDataRecomputeSkipped:\s*true/);
});
