import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('signal ingestion only queues heavy company reprocessing', async () => {
  const sql = await read('db/migrations/144_origination_reprocessing_queue.sql');
  assert.match(sql, /origination_reprocessing_queue/);
  assert.match(sql, /enqueue_company_origination_reprocessing/);
  assert.match(sql, /process_origination_reprocessing_queue/);
  assert.doesNotMatch(sql, /perform public\.refresh_company_factor_snapshots\(new\.company_id/i);
  assert.doesNotMatch(sql, /perform public\.refresh_company_origination_brief_v1\(v_company_id\)/i);
});

test('derived reprocessing is bounded and scheduled independently from capture', async () => {
  const sql = await read('db/migrations/145_origination_reprocessing_schedule.sql');
  assert.match(sql, /origination-derived-reprocessing/);
  assert.match(sql, /process_origination_reprocessing_queue\(25\)/);
  assert.match(sql, /\*\/5 \* \* \* \*/);
});

test('final resolver v4 requires verified CNPJ identity and quarantines conflicts', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  assert.match(sql, /candidate_role in \('operating_company','operating_issuer'\)/);
  assert.match(sql, /coalesce\(c\.cnpj_valid,false\)/);
  assert.match(sql, /website_identity_capture,status/);
  assert.match(sql, /canonical_key_conflict/);
  assert.match(sql, /domain_cnpj_conflict/);
  assert.match(sql, /automatic_deterministic_identity_v4/);
  assert.match(sql, /auto_resolve_verified_candidate_entities_v4\(50\)/);
});

test('resolver v4 never writes generated Company Master columns', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  const insertHeader = sql.match(/insert into public\.companies\(([\s\S]*?)\) values/i)?.[1] ?? '';
  for (const generated of ['normalized_name', 'segment', 'subsegment', 'website', 'geography']) {
    assert.doesNotMatch(insertHeader, new RegExp(`\\b${generated}\\b`));
  }
  assert.match(sql, /normalized_name, segment, subsegment, website and geography are generated by PostgreSQL/);
});

test('resolver runtime binds ON CONFLICT to the named unique constraint', async () => {
  const sql = await read('db/migrations/151_candidate_entity_resolution_v5_conflict_constraint.sql');
  assert.match(sql, /company_discovery_links_company_candidate_unique/);
  assert.match(sql, /pg_get_functiondef/);
  assert.match(sql, /ON CONFLICT ON CONSTRAINT company_discovery_links_company_candidate_unique/);
});

test('company changes enqueue derived reprocessing instead of synchronous brief refresh', async () => {
  const sql = await read('db/migrations/150_candidate_entity_resolution_v4.sql');
  assert.match(sql, /trg_refresh_company_origination_brief_from_company_v2/);
  assert.match(sql, /enqueue_company_origination_reprocessing\(new\.id,'origination_brief_dependency:companies'\)/);
  assert.doesNotMatch(sql, /perform public\.refresh_company_origination_brief_v1\(new\.id\)/);
});

test('verified operating issuers enter origination analytics without becoming credit-approved', async () => {
  const sql = await read('db/migrations/148_operating_issuer_resolution_and_analytics_fix.sql');
  assert.match(sql, /excluded_from_qualification',false/);
  assert.match(sql, /excluded_from_scoring',false/);
  assert.match(sql, /credit_approval_separate',true/);
});

test('verified real entities enter origination analytics without becoming credit-approved', async () => {
  const sql = await read('db/migrations/147_origination_entity_eligibility_gate.sql');
  assert.match(sql, /verified_entity_ready_for_origination_qualification/);
  assert.match(sql, /origination_analytics_eligible/);
  assert.match(sql, /credit_approval_separate/);
  assert.match(sql, /credit_review_status',''\)<>'rejected'/);
});

test('candidate promotion refreshes monitoring and recomputes downstream artifacts', async () => {
  const service = await read('backend/src/services/searchProfileCaptureService.ts');
  assert.match(service, /derivedDataRecomputed/);
  assert.match(service, /await this\.hooks\.recomputeDerivedData\(companyId\)/);
  assert.doesNotMatch(service, /recomputeDerivedDataSkipped:\s*true/);
  assert.doesNotMatch(service, /derivedDataRecomputeSkipped:\s*true/);
});

test('scheduled capture serializes sources within each company and closes downstream intelligence', async () => {
  const workflow = await read('.github/workflows/capture.yml');
  const runner = await read('scripts/capture/run-bounded-capture-batch.ts');
  assert.match(runner, /parallel_between_companies_serial_within_company/);
  assert.match(runner, /for \(const target of group\) \{\s*await runTarget\(target, workerId\);/s);
  assert.match(workflow, /Recompute qualification patterns scores and ranking/);
  assert.match(workflow, /Materialize daily DCM outreach queue/);
});

test('Supabase bootstrap and read paths do not seed or recompute implicitly', async () => {
  const service = await read('backend/src/services/platformService.ts');
  assert.match(service, /async bootstrap\(\) \{\s*if \(env\.useSupabase\) \{\s*return \{ mode: 'real'/s);
  assert.match(service, /private async ensureDerivedData\(\) \{\s*if \(env\.useSupabase\) return;/s);
  assert.match(service, /completeCompanies/);
});

test('news funding recency suppresses stale commercial urgency without deleting history', async () => {
  const recency = await read('backend/src/lib/candidateMediaRecency.ts');
  const semantics = await read('backend/src/services/candidateNewsSemanticsService.ts');
  assert.match(recency, /DEFAULT_MAX_FUNDING_AGE_DAYS = 365/);
  assert.match(recency, /historical_funding_signal/);
  assert.match(recency, /commercial_queue: false/);
  assert.match(recency, /explicitFundingNeed: false/);
  assert.match(semantics, /SEMANTICS_VERSION = 4/);
  assert.match(semantics, /applyCandidateMediaRecencyGuard/);
});

test('daily outreach is materialized from ranking without fabricated contacts or auto-send', async () => {
  const sql = await read('db/migrations/20260820170500_close_dcm_outreach_loop.sql');
  const runner = await read('scripts/materialize-dcm-daily-outreach.ts');
  assert.match(sql, /from public\.ranking_v2/);
  assert.match(sql, /company_origination_brief_v1/);
  assert.match(sql, /'Contato a identificar'/);
  assert.match(sql, /'missing_data'/);
  assert.match(sql, /'autoSend',false/);
  assert.match(sql, /'never_fabricate_contact'/);
  assert.match(runner, /dcm_daily_outreach_autosend_detected/);
});

test('outreach learning stays human-governed before any rule is applied', async () => {
  const sql = await read('db/migrations/20260820170500_close_dcm_outreach_loop.sql');
  const api = await read('api/dcm-outreach-learning.ts');
  assert.match(sql, /pending_review/);
  assert.match(sql, /dcm_outreach_learning_rules/);
  assert.match(api, /review_feedback/);
  assert.match(api, /set_rule_status/);
  assert.match(api, /reviewed_by/);
});

test('Paperclip is an audited control plane inside the official stack', async () => {
  const endpoint = await read('api/paperclip.ts');
  const migration = await read('db/migrations/20260820171500_paperclip_real_control_plane.sql');
  const vercel = await read('vercel.json');
  assert.match(endpoint, /createPlatformRepository\('supabase'\)/);
  assert.match(endpoint, /paperclip_commands/);
  assert.match(endpoint, /run_suggested_improvements/);
  assert.match(endpoint, /autoSend: false/);
  assert.match(migration, /paperclip_status_v/);
  assert.match(vercel, /api\/paperclip\.ts/);
  assert.doesNotMatch(vercel, /railway|docker/i);
});

test('production quick actions never fall back to synthetic records', async () => {
  const api = await read('frontend/src/lib/api.ts');
  assert.doesNotMatch(api, /qa_mock_/);
  assert.doesNotMatch(api, /fallback sintético/i);
  assert.match(api, /Quick actions carregadas exclusivamente do backend oficial/);
});

test('People and Capital reuses existing canonical connectors on the bounded runtime', async () => {
  const sql = await read('db/migrations/20260820172500_people_capital_runtime_schedule.sql');
  assert.match(sql, /src_company_careers/);
  assert.match(sql, /src_tech_signals_latam/);
  assert.match(sql, /'bounded_capture'/);
  assert.doesNotMatch(sql, /insert into public\.source_catalog/i);
});

test('Company Detail remains decision-oriented and does not silently assume credit product presence', async () => {
  const page = await read('frontend/src/pages/CompanyDetailPage.tsx');
  assert.match(page, /Thesis \/ Recommendation/);
  assert.match(page, /Structural Qualification/);
  assert.match(page, /Detected Patterns/);
  assert.match(page, /Prediction/);
  assert.match(page, /Deal Risks \/ Pre-Mortem/);
  assert.doesNotMatch(page, /has_credit_product \?\? true/);
});
